### ISSUE TITLE
Update config

### ISSUE THREAD

**Issue by blakeembrey** [typings/tslint-config-typings#12]
We need to get a TSLint 4.x compatible configuration ready soon.

As a side-note, would you mind if I start maintaining this and refresh it using my configuration modified for `.d.ts` files (E.g. semicolons, etc)? Either that, or I can create a new repo for `tslint-config-types` (E.g. @types) but I figured we can just keep using this repo.

**Comment by unional** [comment]
Updating right now. Should be ready in moments. Also, feel free to make changes to it if you see fit. 🌷

**Comment by unional** [comment]
Just tested it. It doesn't need changes besides updating the dependencies. I have my config updated to 4.0 already.
