### ISSUE TITLE
Allow console functions

### ISSUE THREAD

**Issue by blakeembrey** [typings/tslint-config-typings#6]
It's odd to disallow console functions, can we allow them?

**Comment by blakeembrey** [comment]
Also, similar feeling about shadowed variable errors - what do you think?

**Comment by unional** [comment]
console yes. Shadowed variable not likely. These targets tests, so shadowing is not a good idea and should not happen to begin with.

**Comment by blakeembrey** [comment]
@unional Yes, it's pretty easy to happen. For example, https://github.com/types/npm-redis/blob/master/test.ts. I had to use `err,`err1`,`err2`just to avoid this. Linting should help, not get in the way of a regular code pattern -`err` is especially common in node callback style.

**Comment by unional** [comment]
I see. I work mostly on browser and with at least promise. I can see your point and it does happens often in node callback style.
